version: "3.9"
services:
  db:
    image: postgres
    container_name: api_gastos_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: gastos_db
    ports:
      - "5432:5432"